blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.gg/JE7nhX6mD8
    about: Ask questions and discuss with other marimo users.
  - name: Questions & Discussions
    url: https://github.com/marimo-team/marimo/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
