name: Build and Deploy Docs

on:
  # Deploy on push to main
  push:
    branches: [main]
  # Deploy on workflow dispatch
  workflow_dispatch: {}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: 🥚 Install hatch
        run: pip install hatch

      - name: 📚 Build docs
        run: hatch run docs:build

      - name: ⚡ Install Vercel CLI
        run: npm install --global vercel@latest

      - name: ⬇️ Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: 🚀 Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
